Constants and Applications updates
MarinaKlejevskaja/mortgage pull request #12
Opened 2023-04-15 16:36 UTC by MarinaKlejevskaja

Code refactored
Constants put mapping added
Applications values updated to connect to Users, get and post api added
data.sql reorganized to create users before applications
UsersSerializer added

2023-04-15 19:06 UTC, bandysiu requested changes
Take my comments with a grain of salt. Not all comments have to be addressed and if you dissagree just reply to my comment or explain the question :) Sorry for the amount of comments tho, haha :DD

2023-04-15 19:06 UTC, bandysiu commented on src/main/java/com/academy/mortgage/services/ConstantsService.java
> +    public Constants updateConstants(Constants updatedConstants) {
You should create a seperate class for Request body. On the same note - Response body aswell

2023-04-15 19:06 UTC, bandysiu commented on src/main/resources/application.properties
>  springdoc.swagger-ui.path=/api-docs
So, does swagger work? :D

2023-04-15 19:06 UTC, bandysiu commented on src/main/resources/data.sql
> +    leasing_amount        BIGINT       NOT NULL,
Can you pass a 1,2222 to a bigint? If not should be a float?

2023-04-15 20:32 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +import org.springframework.web.bind.annotation.*;
ok, thanks for pointing this out, will update this with the next commit

2023-04-15 20:34 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +    @GetMapping()
will need more clarification on this comment. My understanding was that each entity has its own service and controllers

2023-04-15 20:35 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/controllers/ConstantsController.java
>  @RequestMapping("/api")
oh, I think now I get the previous comment :)

2023-04-15 20:36 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/controllers/ConstantsController.java
> +    @PutMapping("/constants")
ok, will read more about the proper api names and we can discuss on Monday the big picture

2023-04-15 20:37 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/model/Applications.java
> +    private long consumerLoans; //max 9223372036854775807
ok, will update this with the next commit. Just to confirm we should replace all primitive types with wrapper classes in our entity classes?

2023-04-15 20:41 UTC, bandysiu commented on src/main/java/com/academy/mortgage/model/Applications.java
> +    private long consumerLoans; //max 9223372036854775807
Yup

2023-04-15 20:41 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +    public void serialize(Users user, JsonGenerator jgen, SerializerProvider provider) throws IOException {
this serializer class solves the issue with lazy fetch as once I added FK to applications entity for OneToOne connection to Users, it was not processing the Get request.

2023-04-15 20:41 UTC, bandysiu commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +import org.springframework.web.bind.annotation.*;
You dont have to, just wanted to point out what is the convention with imports :)

2023-04-15 20:42 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +    public void serialize(Users user, JsonGenerator jgen, SerializerProvider provider) throws IOException {
and also instead of returning all fields from users i return only id

2023-04-15 20:43 UTC, bandysiu commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +    public void serialize(Users user, JsonGenerator jgen, SerializerProvider provider) throws IOException {
I dont think I quite understand the idea. Note, one to one relations should be avoided, since they are kind of useless

2023-04-15 20:44 UTC, MarinaKlejevskaja commented on src/main/resources/data.sql
> +    leasing_amount        BIGINT       NOT NULL,
yes, didn't think it through. As usually I saw these values more like a rounded numbers rather than the ones with decimals. But maybe user will decide to add cents to the values as well... will update to float.

2023-04-15 20:53 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +        this(null);
this is some witchcraft from the internet that helps this serializer thing work. without it the get request is error 500 ¯\_(ツ)_/¯ Would be glad to know some best practices to deal with this     
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonSerialize(using = UsersSerializer.class)
    private Users userId;

2023-04-15 20:56 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/services/ConstantsService.java
> +    public Constants updateConstants(Constants updatedConstants) {
Hm, need to google this thing as don't recall us creating such classes  :)

2023-04-15 20:57 UTC, MarinaKlejevskaja commented on src/main/resources/application.properties
>  springdoc.swagger-ui.path=/api-docs
noooo, didn't try to figure it out though as I am used to postman :D will look into it again :)

2023-04-15 21:41 UTC, bandysiu commented on src/main/resources/application.properties
>  springdoc.swagger-ui.path=/api-docs
Oh, but postman works without problems?

2023-04-16 08:31 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +import org.springframework.web.bind.annotation.*;
When I import @RequestBody it automatically replaces all the below imports with one wildcard import:
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

2023-04-16 08:50 UTC, bandysiu commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +import org.springframework.web.bind.annotation.*;
Yeah, you can change this in settings so It won't do that

2023-04-16 08:51 UTC, bandysiu commented on src/main/java/com/academy/mortgage/controllers/ApplicationsController.java
> +import org.springframework.web.bind.annotation.*;
Just leave it as is for now :D

2023-04-16 09:28 UTC, MarinaKlejevskaja commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +    public void serialize(Users user, JsonGenerator jgen, SerializerProvider provider) throws IOException {
As we discussed during the meeting, the idea is that one user may have only one application and one application can have only one user. Although I start doubting it as if we have co-borrowers, then two users will be assigned to one application. Will discuss this with PO on Monday

2023-04-16 09:46 UTC, MarinaKlejevskaja commented on src/main/resources/application.properties
>  springdoc.swagger-ui.path=/api-docs
yes, Postman works fine. I event tried to use the same dependencies and url path as we had with Saulius during our Spring lecture where we used Swagger and it still didn't work on this project...

2023-04-16 19:56 UTC, swoogie approved these changes

2023-04-16 20:02 UTC, bandysiu commented on src/main/java/com/academy/mortgage/serializers/UsersSerializer.java
> +    public void serialize(Users user, JsonGenerator jgen, SerializerProvider provider) throws IOException {
Yes, but we'd like to store all user applications, even discontinued/expired, not just the active ones

2023-04-17 06:26 UTC, bandysiu approved these changes

2023-04-17 07:55 UTC, merged